image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:v${CI_BUILD_REF_NAME}

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build_latest:
  tags: 
    - mintel
  stage: build
  script:
    - docker build --pull -t $LATEST_IMAGE .
    - docker push $LATEST_IMAGE
  only:
    - master

build_tag:
  tags: 
    - mintel
  stage: build
  script:
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
  only:
    - tags

