---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-auth
---
# Generate a CA Certificate used to sign certificates
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kube-auth-ca
  namespace: "kube-auth"
  labels:
    app.kubernetes.io/component: identity-service
    app.kubernetes.io/name: dex
    app.kubernetes.io/part-of: dex
spec:
  secretName: kube-auth-ca
  duration: 87600h
  issuerRef:
    kind: ClusterIssuer
    name: global-ss-issuer
  commonName: "ca.kube-auth"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: kube-auth-ca
  namespace: "kube-auth"
  labels:
    app.kubernetes.io/component: identity-service
    app.kubernetes.io/name: dex
    app.kubernetes.io/part-of: dex
spec:
  ca:
    secretName: kube-auth-ca
